name: build

on:
  push:
  pull_request:
  schedule:
    # https://crontab.guru/
    # At 12:00 AM, only on Monday
    - cron: 0 0 * * 1

env:
  build-folder: build
  python-version: 3.9

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - name: Ubuntu GCC x86 64 Release
            os: ubuntu-latest
            compiler: gcc
            arch: x86_64
            build_type: Release

          - name: Ubuntu Clang x86 64 Release
            os: ubuntu-latest
            compiler: clang
            arch: x86_64
            build_type: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: Install requirements
        run: python -m pip install --upgrade pip conan

      - name: Install dependencies
        run: conan install . -if ${{ env.build-folder }} --build outdated
          -pr .conan/profiles/profile.jinja -pr:b .conan/profiles/profile.jinja
        env:
          Compiler: ${{ matrix.config.compiler }}
          Version: ${{ matrix.config.version }}
          Arch: ${{ matrix.config.arch }}
          BuildType: ${{ matrix.config.build_type }}
          Toolset: ${{ matrix.config.toolset }}
          Runtime: ${{ matrix.config.runtime }}

      - name: Build
        run: conan build . -bf ${{ env.build-folder }}

      - name: Test
        run: ctest -C ${{ matrix.config.build_type }}
          --output-on-failure
          --repeat-until-fail 1
          --test-dir ${{ env.build-folder }}
          --output-junit report.xml
          --timeout 120
